### PR TITLE
Convert quiet to bool in UploadDaemon too, to fix build after refactoring.

### PR DESCRIPTION
**Pull request by ghen2**
UploadDaemon build was broken by https://github.com/SBFspot/SBFspot/commit/e6e975fbc2d24bb77ceb07fe8371cbc08246f97b;

```
../SBFspotUploadCommon/PVOutput.h:46:12: error: conflicting declaration 'int quiet'
../SBFspotUploadCommon/Configuration.h:48:12: error: conflicting declaration 'int quiet'
main.cpp:49:5: error: conflicting declaration 'int quiet'
```

### CODE REVIEW

**Comment by ghen2** [comment]
SBFspotUploadService might need a similar fix, but I'm not using or building this (on Linux).
