### ISSUE TITLE
Arch Linux: SBFspot does not compile with BOOST 1.58

### ISSUE THREAD

**Issue by SBFspot** [SBFspot/SBFspot#115]
Hi,

I'm running Arch Linux on a Raspberry with SBFspot and this was fine until a few days ago. I installed the latest Arch updates and since then SBFspot is only producing errors like this:
error while loading shared libraries: libboost_date_time.so.1.57.0: cannot open shared object file: No such file or directory

Can you help me? What's wrong?

#### Attachments
[boost_ext.zip](https://www.codeplex.com/Download/AttachmentDownload.ashx?ProjectName=SBFspot&WorkItemId=110&FileAttachmentId=1458729)

#### This work item was migrated from CodePlex
CodePlex work item ID: '110'
Vote count: '1'

**Comment by SBFspot** [comment]
[SBF@5/05/2015]
SBFspot is compiled with boost libs 1.57.0 and now boost is upgraded to a higher version.
Try to recompile SBFspot with the new boost libs

**Comment by SBFspot** [comment]
[kst78@9/05/2015]
Thanks for the response.
I tried to compile it new but got only errors:

test -d bin/Release || mkdir -p bin/Release
test -d obj/Release || mkdir -p obj/Release
g++ -Wall -O2  -c boost_ext.cpp -o obj/Release/boost_ext.o
boost_ext.cpp: In function 'time_t to_time_t(boost::gregorian::date)':
boost_ext.cpp:46:53: error: call of overloaded 'to_time_t(boost::posix_time::ptime)' is ambiguous
  return time_t(to_time_t(boost::posix_time::ptime(d)));
                                                     ^
boost_ext.cpp:46:53: note: candidates are:
boost_ext.cpp:37:8: note: time_t to_time_t(boost::posix_time::ptime)
time_t to_time_t(boost::posix_time::ptime t)
        ^
In file included from /usr/include/boost/date_time/posix_time/posix_time_io.hpp:21:0,
                 from /usr/include/boost/date_time/posix_time/posix_time.hpp:31,
                 from boost_ext.h:39,
                 from boost_ext.cpp:35:
/usr/include/boost/date_time/posix_time/conversion.hpp:35:15: note: time_t boost::posix_time::to_time_t(boost::posix_time::ptime)
   std::time_t to_time_t(ptime pt)
               ^
boost_ext.cpp:47:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
makefile:92: recipe for target 'obj/Release/boost_ext.o' failed

**Comment by SBFspot** [comment]
[SBF@14/05/2015]
Try to remove and reinstall boost libs

**Comment by SBFspot** [comment]
[kst78@14/05/2015]
Thanks, I already tried to remove boost and boost-libs and then reinstalled them. Unfortunately without success.

I even tried with a second device and did a complete fresh installation and get the exact same error message.

Any other ideas? Can you reproduce the problem?

**Comment by SBFspot** [comment]
[SBF@15/05/2015]
No, I can't reproduce as we all have Raspbian installed...
I can try Arch linux on my second RPi to help you out, but how did you install it? There is no Arch image at https://www.raspberrypi.org/downloads/

**Comment by SBFspot** [comment]
[SBF@15/05/2015]
I think I found it... http://archlinuxarm.org/platforms/armv6/raspberry-pi
But why Arch Linux?

**Comment by SBFspot** [comment]
[kst78@15/05/2015]
Arch img can be downloaded here: http://downloads.raspberrypi.org/arch/images/arch-2014-06-22/

In earlier days it was also directly linked on the main raspberry page (https://www.raspberrypi.org/downloads/). Unfortunately this is not avialable anymore.


Why Arch?
I used for a long time raspbian on one raspberry and ubuntu on the other. I use them currently SBFspot (which is by the way a great tool!! Thanks).
The Pi's ran stable as long as I didn't touch them. But then I wanted to change something (e.g. move them from one place to the other and connect them via wifi instead of ethernet and recognized the sources are outdated and I couldn't update, etc.
I don't want to install raspbian or ubuntu new from scratch every time a new version is released.

Maybe I'm wrong... I'm not that experienced in linux.

So I'm now "testing" since a few month Arch because they advert it can always be updates:
"Always Up to Date
New software versions are packaged as they are released, ensuring you are always on the leading edge."

Would be very kind if you could help me to fix this boost problem. I guess this will sooner or later also happen on raspbian when they update the boost library.

Thanks.

**Comment by SBFspot** [comment]
[aldesr@16/05/2015]

Arch Linux ARM images would best downloaded from :
http://os.archlinuxarm.org/os

ArchLinuxARM-rpi-latest.tar.gz
or
ArchLinuxARM-rpi-2-latest.tar.gz

It looks like the most recent image is older than boost libs 1.58.0 release.

One option might to rollback to 1.57.0 temporarily
https://wiki.archlinux.org/index.php/Downgrading_packages

**Comment by SBFspot** [comment]
[SBF@16/05/2015]
I installed arch linux on my spare RPi but I'm unable to install boost libs
```
[root@alarmpi ~]# pacman -S libboost-all-dev
error: failed to initialize alpm library
(database is incorrect version: /var/lib/pacman/)
error:   try running pacman-db-upgrade
[root@alarmpi ~]# pacman-db-upgrade
==> Pre-4.2 database format detected - upgrading...
[root@alarmpi ~]# pacman -S libboost-all-dev
error: target not found: libboost-all-dev

```

**Comment by SBFspot** [comment]
[kst78@16/05/2015]
libboost-all-dev is in Arch called "boost-libs"

**Comment by SBFspot** [comment]
[SBF@24/05/2015]
Finally installed my RPi 2 with Arch Linux using [this](http://archlinuxarm.org/platforms/armv6/raspberry-pi) procedure.
It's for Raspberry 1 (arm 6) while my RPi 2 should be [arm 7](https://www.raspberrypi.org/raspberry-pi-2-on-sale/) - really strange. If someone can help me on this, please do.
Anyway, it works now:
```
[root@alarmpi ~]# uname -a
Linux alarmpi 3.18.10-2-ARCH #1 PREEMPT Fri Mar 27 19:58:06 MDT 2015 armv6l GNU/Linux

```

**Comment by SBFspot** [comment]
[kst78@25/05/2015]
I guess the "correct" installation procedure for a RPi 2 would be this here: http://archlinuxarm.org/platforms/armv7/broadcom/raspberry-pi-2

But if your RPi is working, can you reproduce the boost problem with SBFspot?

**Comment by SBFspot** [comment]
[SBF@25/05/2015]
When I use the armv7 procedure, the green LED on my RPi2 is blinking 7 times which means "kernel.img" not found. Indeed, on the boot partition there is only "kernel7.img"
http://elinux.org/R-Pi_Troubleshooting#Green_LED_blinks_in_a_specific_pattern

I was able to reproduce it and I'm testing the solution now

**Comment by SBFspot** [comment]
[SBF@25/05/2015]
You can find the changes in the attached zip file.
Extract the files in your sbfspot.3/SBFspot directory and recompile

**Comment by SBFspot** [comment]
**Issue closed by _SBF_ with comment**
Fixed in V3.1.0

**Reason closed**
Fixed
